import { BoardTemplate } from '../types';

export const BUILT_IN_TEMPLATES: BoardTemplate[] = [
  {
    id: 'blank',
    name: 'Blank Board',
    description: 'Start fresh with empty columns',
    icon: '📋',
    isBuiltIn: true,
    columns: [
      { title: 'To Do' },
      { title: 'In Progress' },
      { title: 'Done', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'demo',
    name: 'Demo Board',
    description: 'Sample board with tasks to explore features',
    icon: '🚀',
    isBuiltIn: true,
    columns: [
      { title: 'To Do', color: '#3b82f6' },
      { title: 'In Progress', color: '#eab308' },
      { title: 'Review', color: '#8b5cf6' },
      { title: 'Done', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'Bug', color: '#ef4444' },
      { name: 'Feature', color: '#22c55e' },
      { name: 'Enhancement', color: '#3b82f6' },
      { name: 'Documentation', color: '#8b5cf6' },
      { name: 'Urgent', color: '#f97316' },
    ],
    tasks: [
      { 
        title: 'Critical server issue - needs immediate fix', 
        description: 'The main API endpoint is returning 500 errors for 10% of requests. This is affecting production users.',
        columnIndex: 1, 
        labelIndices: [0, 4],
        priority: 'critical',
      },
      { 
        title: 'Implement user authentication', 
        description: 'Add login/logout functionality with JWT tokens.\n\nRequirements:\n- Email/password login\n- Remember me option\n- Password reset flow',
        columnIndex: 0, 
        labelIndices: [1],
        priority: 'high',
      },
      { 
        title: 'Fix navigation menu on mobile', 
        description: 'The hamburger menu doesn\'t close after selecting an item on iOS devices.',
        columnIndex: 1, 
        labelIndices: [0],
        priority: 'high',
      },
      { 
        title: 'Add dark mode support', 
        description: 'Implement a theme toggle that switches between light and dark modes. Should respect system preferences by default.',
        columnIndex: 2, 
        labelIndices: [2],
        priority: 'medium',
      },
      { 
        title: 'Write API documentation', 
        description: 'Document all REST endpoints with examples using OpenAPI/Swagger format.',
        columnIndex: 0, 
        labelIndices: [3],
        priority: 'medium',
      },
      { 
        title: 'Optimize database queries', 
        description: 'The dashboard page is slow. Need to add indexes and optimize the most frequent queries.',
        columnIndex: 0, 
        labelIndices: [2],
        priority: 'low',
      },
      { 
        title: 'Add export to PDF feature', 
        description: 'Allow users to export their reports as PDF documents.',
        columnIndex: 0, 
        labelIndices: [1],
        priority: 'low',
      },
      { 
        title: 'Update dependencies', 
        description: 'Review and update all npm packages to latest stable versions.',
        columnIndex: 0, 
        labelIndices: [],
        priority: 'none',
      },
      { 
        title: 'Setup CI/CD pipeline', 
        description: 'Configure GitHub Actions for automated testing and deployment.',
        columnIndex: 3, 
        labelIndices: [2],
        priority: 'medium',
      },
      { 
        title: 'User onboarding flow', 
        description: 'Create a guided tour for new users explaining the main features.',
        columnIndex: 3, 
        labelIndices: [1],
        priority: 'low',
      },
    ],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'project',
    name: 'Project Management',
    description: 'Track project tasks from planning to completion',
    icon: '🎯',
    isBuiltIn: true,
    columns: [
      { title: 'Backlog', color: '#6b7280' },
      { title: 'To Do', color: '#3b82f6' },
      { title: 'In Progress', color: '#eab308' },
      { title: 'Review', color: '#8b5cf6' },
      { title: 'Done', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'Bug', color: '#ef4444' },
      { name: 'Feature', color: '#22c55e' },
      { name: 'Enhancement', color: '#3b82f6' },
      { name: 'Documentation', color: '#8b5cf6' },
      { name: 'High Priority', color: '#f97316' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'agile',
    name: 'Agile Sprint',
    description: 'Manage sprints with user stories and tasks',
    icon: '🏃',
    isBuiltIn: true,
    columns: [
      { title: 'Sprint Backlog', color: '#6b7280' },
      { title: 'In Development', color: '#3b82f6' },
      { title: 'Code Review', color: '#8b5cf6' },
      { title: 'Testing', color: '#f97316' },
      { title: 'Done', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'User Story', color: '#3b82f6' },
      { name: 'Task', color: '#22c55e' },
      { name: 'Bug', color: '#ef4444' },
      { name: 'Blocked', color: '#f97316' },
      { name: 'Technical Debt', color: '#6b7280' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'marketing',
    name: 'Marketing Campaign',
    description: 'Plan and track marketing activities',
    icon: '📢',
    isBuiltIn: true,
    columns: [
      { title: 'Ideas', color: '#6b7280' },
      { title: 'Planning', color: '#3b82f6' },
      { title: 'In Progress', color: '#eab308' },
      { title: 'Review', color: '#8b5cf6' },
      { title: 'Published', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'Social Media', color: '#3b82f6' },
      { name: 'Email', color: '#22c55e' },
      { name: 'Blog', color: '#8b5cf6' },
      { name: 'Video', color: '#ef4444' },
      { name: 'Ads', color: '#f97316' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'content',
    name: 'Content Calendar',
    description: 'Manage content creation workflow',
    icon: '📝',
    isBuiltIn: true,
    columns: [
      { title: 'Ideas', color: '#6b7280' },
      { title: 'Writing', color: '#3b82f6' },
      { title: 'Editing', color: '#f97316' },
      { title: 'Scheduled', color: '#8b5cf6' },
      { title: 'Published', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'Blog Post', color: '#3b82f6' },
      { name: 'Tutorial', color: '#22c55e' },
      { name: 'Case Study', color: '#8b5cf6' },
      { name: 'News', color: '#f97316' },
      { name: 'Urgent', color: '#ef4444' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'hiring',
    name: 'Hiring Pipeline',
    description: 'Track candidates through the hiring process',
    icon: '👥',
    isBuiltIn: true,
    columns: [
      { title: 'Applied', color: '#6b7280' },
      { title: 'Screening', color: '#3b82f6' },
      { title: 'Interview', color: '#eab308' },
      { title: 'Offer', color: '#8b5cf6' },
      { title: 'Hired', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'Engineering', color: '#3b82f6' },
      { name: 'Design', color: '#ec4899' },
      { name: 'Marketing', color: '#22c55e' },
      { name: 'Sales', color: '#f97316' },
      { name: 'Senior', color: '#8b5cf6' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'personal',
    name: 'Personal Tasks',
    description: 'Organize your daily life',
    icon: '🏠',
    isBuiltIn: true,
    columns: [
      { title: 'Inbox', color: '#6b7280' },
      { title: 'Today', color: '#ef4444' },
      { title: 'This Week', color: '#eab308' },
      { title: 'Someday', color: '#3b82f6' },
      { title: 'Done', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'Work', color: '#3b82f6' },
      { name: 'Personal', color: '#22c55e' },
      { name: 'Health', color: '#ef4444' },
      { name: 'Finance', color: '#f97316' },
      { name: 'Learning', color: '#8b5cf6' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'bugtracker',
    name: 'Bug Tracker',
    description: 'Track and resolve software bugs',
    icon: '🐛',
    isBuiltIn: true,
    columns: [
      { title: 'Reported', color: '#ef4444' },
      { title: 'Confirmed', color: '#f97316' },
      { title: 'In Progress', color: '#eab308' },
      { title: 'Testing', color: '#8b5cf6' },
      { title: 'Resolved', color: '#22c55e', isCompleteColumn: true },
    ],
    labels: [
      { name: 'Critical', color: '#ef4444' },
      { name: 'High', color: '#f97316' },
      { name: 'Medium', color: '#eab308' },
      { name: 'Low', color: '#22c55e' },
      { name: 'Won\'t Fix', color: '#6b7280' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
];
