import { BoardTemplate } from '../types';

export const BUILT_IN_TEMPLATES: BoardTemplate[] = [
  {
    id: 'blank',
    name: 'Blank Board',
    description: 'Start fresh with empty columns',
    icon: '📋',
    isBuiltIn: true,
    columns: [
      { title: 'To Do' },
      { title: 'In Progress' },
      { title: 'Done' },
    ],
    labels: [],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'project',
    name: 'Project Management',
    description: 'Track project tasks from planning to completion',
    icon: '🎯',
    isBuiltIn: true,
    columns: [
      { title: 'Backlog' },
      { title: 'To Do' },
      { title: 'In Progress' },
      { title: 'Review' },
      { title: 'Done' },
    ],
    labels: [
      { name: 'Bug', color: '#ef4444' },
      { name: 'Feature', color: '#22c55e' },
      { name: 'Enhancement', color: '#3b82f6' },
      { name: 'Documentation', color: '#8b5cf6' },
      { name: 'High Priority', color: '#f97316' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'agile',
    name: 'Agile Sprint',
    description: 'Manage sprints with user stories and tasks',
    icon: '🏃',
    isBuiltIn: true,
    columns: [
      { title: 'Sprint Backlog' },
      { title: 'In Development' },
      { title: 'Code Review' },
      { title: 'Testing' },
      { title: 'Done' },
    ],
    labels: [
      { name: 'User Story', color: '#3b82f6' },
      { name: 'Task', color: '#22c55e' },
      { name: 'Bug', color: '#ef4444' },
      { name: 'Blocked', color: '#f97316' },
      { name: 'Technical Debt', color: '#6b7280' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'marketing',
    name: 'Marketing Campaign',
    description: 'Plan and track marketing activities',
    icon: '📢',
    isBuiltIn: true,
    columns: [
      { title: 'Ideas' },
      { title: 'Planning' },
      { title: 'In Progress' },
      { title: 'Review' },
      { title: 'Published' },
    ],
    labels: [
      { name: 'Social Media', color: '#3b82f6' },
      { name: 'Email', color: '#22c55e' },
      { name: 'Blog', color: '#8b5cf6' },
      { name: 'Video', color: '#ef4444' },
      { name: 'Ads', color: '#f97316' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'content',
    name: 'Content Calendar',
    description: 'Manage content creation workflow',
    icon: '📝',
    isBuiltIn: true,
    columns: [
      { title: 'Ideas' },
      { title: 'Writing' },
      { title: 'Editing' },
      { title: 'Scheduled' },
      { title: 'Published' },
    ],
    labels: [
      { name: 'Blog Post', color: '#3b82f6' },
      { name: 'Tutorial', color: '#22c55e' },
      { name: 'Case Study', color: '#8b5cf6' },
      { name: 'News', color: '#f97316' },
      { name: 'Urgent', color: '#ef4444' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'hiring',
    name: 'Hiring Pipeline',
    description: 'Track candidates through the hiring process',
    icon: '👥',
    isBuiltIn: true,
    columns: [
      { title: 'Applied' },
      { title: 'Screening' },
      { title: 'Interview' },
      { title: 'Offer' },
      { title: 'Hired' },
    ],
    labels: [
      { name: 'Engineering', color: '#3b82f6' },
      { name: 'Design', color: '#ec4899' },
      { name: 'Marketing', color: '#22c55e' },
      { name: 'Sales', color: '#f97316' },
      { name: 'Senior', color: '#8b5cf6' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'personal',
    name: 'Personal Tasks',
    description: 'Organize your daily life',
    icon: '🏠',
    isBuiltIn: true,
    columns: [
      { title: 'Inbox' },
      { title: 'Today' },
      { title: 'This Week' },
      { title: 'Someday' },
      { title: 'Done' },
    ],
    labels: [
      { name: 'Work', color: '#3b82f6' },
      { name: 'Personal', color: '#22c55e' },
      { name: 'Health', color: '#ef4444' },
      { name: 'Finance', color: '#f97316' },
      { name: 'Learning', color: '#8b5cf6' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
  {
    id: 'bugtracker',
    name: 'Bug Tracker',
    description: 'Track and resolve software bugs',
    icon: '🐛',
    isBuiltIn: true,
    columns: [
      { title: 'Reported' },
      { title: 'Confirmed' },
      { title: 'In Progress' },
      { title: 'Testing' },
      { title: 'Resolved' },
    ],
    labels: [
      { name: 'Critical', color: '#ef4444' },
      { name: 'High', color: '#f97316' },
      { name: 'Medium', color: '#eab308' },
      { name: 'Low', color: '#22c55e' },
      { name: 'Won\'t Fix', color: '#6b7280' },
    ],
    tasks: [],
    createdAt: 0,
    updatedAt: 0,
  },
];
